# Site settings
title: algurpe's educational blog
email: algurpe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging with *jekyll* and *github pages*.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://algurpe.github.io" # the base hostname & protocol for your site
twitter_username: algurpe2
github_username:  algurpe

# Build settings
markdown: kramdown
